name: Release SuperRez Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Compile TypeScript
      run: npm run compile

    - name: Package extension
      run: |
        npm install -g vsce
        vsce package

    - name: Get version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: SuperRez v${{ steps.version.outputs.version }}
        body: |
          # SuperRez v${{ steps.version.outputs.version }}
          
          ## 🚀 Cost-Aware AI Development Assistant
          
          **95% cost reduction vs SuperClaude** - Local-first architecture with smart AI orchestration
          
          ### 🛠️ Features in this release:
          - Session management with project discovery
          - Local security and performance analysis (FREE)
          - AI tool detection and smart routing
          - Cost tracking and budget protection
          - 8 VSCode commands ready to use
          
          ### 💰 Cost Savings:
          - **SuperClaude**: $200-400/month
          - **SuperRez**: $0-20/month
          
          ### 📥 Installation:
          1. Download the `.vsix` file below
          2. Open VSCode → Extensions → Install from VSIX
          3. Open Command Palette → `SuperRez: Start Session`
          4. Start saving money immediately!
          
          ### 🤖 AI Tools Supported:
          - Claude Code (best for analysis)
          - Gemini CLI (cost-effective)
          - GitHub Copilot (code completion)
          - Ollama (free local models)
          - Cursor (IDE integration)
          - Kimi/Moonshot (advanced coding)
          
          ### 🛡️ Local Analysis (100% FREE):
          - Security vulnerability scanning
          - Performance bottleneck detection
          - Code quality analysis
          - No API calls required!
          
          **Join our Discord**: https://discord.gg/YOUR_INVITE_LINK
          **GitHub**: https://github.com/rezurx/SuperRez
          
          *Proving that local-first can beat cloud-first while saving developers money.*
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./superrez-${{ steps.version.outputs.version }}.vsix
        asset_name: superrez-${{ steps.version.outputs.version }}.vsix
        asset_content_type: application/zip

    - name: Discord Release Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      with:
        args: |
          🎉 **SuperRez v${{ steps.version.outputs.version }} Released!**
          
          **The SuperClaude alternative that saves you 95% on AI costs is here!**
          
          🛠️ **What's New:**
          - Session management with project discovery
          - FREE security and performance analysis
          - Smart AI routing for 6+ AI tools
          - Cost tracking and budget protection
          
          💰 **Cost Savings:**
          SuperClaude: $200-400/month → SuperRez: $0-20/month
          
          📥 **Download**: ${{ steps.create_release.outputs.html_url }}
          
          🤝 **Community**: Star the repo and share your feedback!
          
          *Local-first beats cloud-first - download now and start saving!*